name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Code ophalen uit GitHub
      uses: actions/checkout@v3

    - name: Node.js installeren
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Dependencies installeren
      run: npm install

    - name: App bouwen
      run: npm run build

    - name: Deployen naar Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'devops-inleveropdracht'  # jouw Azure App Service naam
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
